name: Dependency Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Cài và nâng cấp pip-audit lên bản mới nhất để hỗ trợ SARIF
        pip install --upgrade pip-audit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pip-audit scan (JSON)
      run: |
        pip-audit -r requirements.txt --format json --output results.json

    - name: Convert JSON to SARIF
      run: |
        pip install sarif-tools
        sarif-tools from-pip-audit results.json > results.sarif

    - name: Upload SARIF results (cho Security tab trên GitHub)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: dependency-scan
