name: Dependency Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Cài và nâng cấp pip-audit lên bản mới nhất để hỗ trợ SARIF
        pip install --upgrade pip-audit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pip-audit scan
      run: |
        # Quét dependencies, xuất file SARIF
        pip-audit -r requirements.txt --format sarif --output results.sarif

        # Nếu có vuln nghiêm trọng thì fail job (bạn có thể tùy chỉnh ignore)
        if pip-audit -r requirements.txt; then
          echo "✅ No critical vulns found"
        else
          echo "❌ Vulns found!"
          exit 1
        fi

    - name: Upload SARIF results (cho Security tab trên GitHub)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: dependency-scan
